In [1]:
import numpy as np

In [3]:
x = np.array([[-3.5],
              [-2.6],
              [0.3],
              [1.6]
])

In [5]:
y = np.array([[-17.3],
              [-13.8],
              [-1.9],
              [3.8]])
y

array([[-17.3],
       [-13.8],
       [ -1.9],
       [  3.8]])

In [6]:
A = np.concatenate(((np.ones(shape=(4,1))),x),axis=1)
A

array([[ 1. , -3.5],
       [ 1. , -2.6],
       [ 1. ,  0.3],
       [ 1. ,  1.6]])

In [7]:
A.T@A

array([[ 4.  , -4.2 ],
       [-4.2 , 21.66]])

In [8]:
np.linalg.inv(A.T@A)

array([[0.31391304, 0.06086957],
       [0.06086957, 0.05797101]])

In [10]:
w = np.linalg.inv(A.T@A) @ A.T @ y
w

array([[-2.96121739],
       [ 4.13217391]])

In [12]:
Y_he  = A@w
Y_he 

array([[-17.42382609],
       [-13.70486957],
       [ -1.72156522],
       [  3.65026087]])

In [13]:
Y_he - y

array([[-0.12382609],
       [ 0.09513043],
       [ 0.17843478],
       [-0.14973913]])

In [14]:
mse  = 1/4 * np.linalg.norm(Y_he - y)**2
mse

np.float64(0.019660869565217173)